### ISSUE TITLE
[script] [train.lic] add fang_cove_override_town

### ISSUE THREAD

**Issue by Kiriawen** [elanthia-online/dr-scripts#7003]
```yaml
hometown: Crossing
# If hometown is Fang Cove, some scripts (athletics, burgle, checkfavors, favor, and crossing-repair, among others - see base-help.yaml
# for updated list) will not run properly at all, or require extra settings. This setting gives a town for all of
# the above scripts to use as a faux hometown so they function properly. Make it close to where you usually enter Fang Cove.
fang_cove_override_town:
```
needs this added as it uses `hometown:` to know where to train stats.
